<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>APATERNO</th>
        <th>AMATERNO</th>
        <th>NOMBRES</th>
        <th>GENERO</th>
        <th>FECHA_NACIMIENTO</th>
        <th>LUGAR_NACIMIENTO</th>
        <th>EDO_CIVIL</th>
        <th>CURP</th>
        <th>DOMICILIO</th>
        <th>CIUDAD</th>
        <th>ESTADO</th>
        <th>EMAIL</th>
        <th>CP</th>
        <th>TELEFONO1</th>
        <th>TELEFONO2</th>
        <th>STATUS</th>
        <th>NOMBRE_TUTOR</th>
        <th>PARENTESCO_TUTOR</th>
        <th>TELEFONO_TUTOR</th>
        <th>RAZON_SOCIAL</th>
        <th>RFC</th>
        <th>USO_CFDI</th>
        <th>FECHA_CREACION</th>

    </tr>
    </thead>
    <tbody>
    @foreach($grupoalumnos as $alumnos)
        <tr>
            <td>{{$alumnos->id}}</td>
            <td>{{$alumnos->apaterno}}</td>
            <td>{{$alumnos->amaterno}}</td>
            <td>{{$alumnos->nombres}}</td>
            <td>{{$alumnos->genero}}</td>
            <td>{{$alumnos->fecha_nac}}</td>
            <td>{{$alumnos->lugar_nac}}</td>
            <td>{{$alumnos->edo_civil}}</td>
            <td>{{$alumnos->curp}}</td>
            <td>{{$alumnos->domicilio}}</td>
            <td>{{$alumnos->ciudad}}</td>
            <td>{{$alumnos->estado}}</td>
            <td>{{$alumnos->email}}</td>
            <td>{{$alumnos->telefono}}</td>
            <td>{{$alumnos->cp}}</td>
            <td>{{$alumnos->telefono2}}</td>
            <td>{{$alumnos->foto}}</td>
            <td>{{$alumnos->status}}</td>
            <td>{{$alumnos->nombre_tutor}}</td>
            <td>{{$alumnos->parentesco_tutor}}</td>
            <td>{{$alumnos->telefono_tutor}}</td>
            <td>{{$alumnos->razon_social}}</td>
            <td>{{$alumnos->rfc}}</td>
            <td>{{$alumnos->uso_cfdi}}</td>
        </tr>
    @endforeach
    </tbody>
</table>